### ISSUE TITLE
Document-details page crashs

### ISSUE THREAD

**Issue by aviriel** [ITDSystems/alvex-project-management#22]
If installing bundle from nexus, any document-details page crashs, because of the following error:

08120016 Failed to execute script 'classpath*:alfresco/web-extension/site-webscripts/document-details/document-workflows.get.js': 08120015 Error: Could not load document workflows for workspace://SpacesStore/1a0b110f-1e09-4ca2-b367-fe25e4964a4e (jar:file:/home/aviriel/alfresco/alfresco-201605/tomcat/webapps/share/WEB-INF/lib/com.alvexcore.share.project-management-1.30-SNAPSHOT.jar!/alfresco/web-extension/site-webscripts/document-details/document-workflows.get.js#1226)

**Comment by ArgentumHeart** [comment]
Fix https://github.com/ITDSystems/alvex-project-management/pull/24

**Comment by aviriel** [comment]
Fixed with https://github.com/ITDSystems/alvex-project-management/pull/24
