### ISSUE TITLE
Проблема отображения после установки

### ISSUE THREAD

**Issue by shin0bi2014** [ITDSystems/alvex-project-management#62]
все ставил по данной инструкции https://github.com/ITDSystems/alvex-project-management
никаких ошибок при установке не было
но вот такой вот результат 
![error-pml](https://cloud.githubusercontent.com/assets/8466842/22961377/83d06ca8-f356-11e6-824e-45ba049fddd7.png)
 
При нажатии каких либо кнопок никаких ошибок в логах не появляется, как будто они вовсе не функциональны. amp создавал с помощью еклипс, Alfresco 5  alfresco-community-installer-201611-EA-linux-x64.bin

**Comment by shin0bi2014** [comment]
поправил, но пришлось поставить все модули какие только есть. Скорей всего или в списке зависимостей для project-management не добавили либо сам накосячил. Однако, появилась другая проблема следующего вида
![error-pml-02](https://cloud.githubusercontent.com/assets/8466842/22965580/4113d436-f36f-11e6-8f9a-e5aab3f3de9e.png)
понятно что связано с локалью, но все другие модули нормально отображают русс яз.

**Comment by aviriel** [comment]
Первое - наша ошибка. Исправляем.
Второе - это не Alvex, это Вы еще что-то установили, у нас после Заместителей сразу "Изменить пароль" идет.

**Comment by shin0bi2014** [comment]
это оказался плагин "статус на работе" или офф. сейчас уже не посмотрю опять пришлось удалить сборку, пока не стабильно к сожалению :(  
скажите а в аддоне alvex-project-management естьпостроение диаграммы ганта?

**Comment by aviriel** [comment]
Нет, диаграммы ганта нет и не будет, она противоречит изначальной идеологии Alvex.
Про первый баг - откатитесь до коммита https://github.com/ITDSystems/alvex-datagrid/tree/b0d994e09d0d508386dc5c07d078e86f3c6515a3 , даталисты заработают на 5.2 (201611 и позднее). А мы пока попробуем сделать так, чтобы оно заработало на всех версиях Alfresco. Предпоследний коммит чинил datagrid в 5.1 one, но сломал в 5.2 community. Последний коммит Вам вряд ли нужен, он принес македонскую локализацию.

**Comment by shin0bi2014** [comment]
понял, проверю. Но я склонялся к последней версии комунити, а на 201611 просто тестил, так как больше шансов увидеть рабочий вариант. будут ошибки отпишусь спасибо
