### ISSUE TITLE
Cannot attach file from repository to workflow

### ISSUE THREAD

**Issue by mat02** [ITDSystems/alvex-project-management#65]
Hi,
I'm using Alfresco Community 5.2e with Alvex version 3.0-SNAPSHOT
When I start new workflow and click Attach from repository there's no list of files/folders presented:
![image](https://user-images.githubusercontent.com/1629659/27388881-0e0022c0-569d-11e7-84e5-c357bbd16fc4.png)

However, if I start workflow from task list everything works as expected:
![image](https://user-images.githubusercontent.com/1629659/27388933-3d7f2b7c-569d-11e7-88a1-8522ad5392e6.png)

I cannot see anything related to this in catalina.out log file.
What can be the cause?

**Comment by aviriel** [comment]
Do I understand correctly that you start a workflow from the dashlet in the project site?

**Comment by mat02** [comment]
Yes, the first case is when starting from the dashlet.
